name       : xev
version    : 1.2.3
release    : 3
source     :
    - https://xorg.freedesktop.org/releases/individual/app/xev-1.2.3.tar.bz2 : 66bc4f1cfa1946d62612737815c34164e4ce40fcebd2c9e1d7e7a1117ad3ad09
license    :
    - GPL-3.0-only
    - MIT
component  : xorg.apps
summary    : Print contents of X events
description: |
    Xev creates a window and then asks the X server to send it events whenever anything happens to the window (such as it being moved, resized, typed in, clicked in, etc.). You can also attach it to an existing window. It is useful for seeing what causes events to occur and to display the information that they contain; it is essentially a debugging and development tool, and should not be needed in normal usage.
builddeps  :
    - pkgconfig(xrandr)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
