name       : xev
version    : 1.2.2
release    : 2
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xev-1.2.2.tar.bz2 : d94ae62a6c1af56c2961d71f5782076ac4116f0fa4e401420ac7e0db33dc314f
license    : GPL-3.0
component  : xorg.apps
summary    : Print contents of X events
description: |
    Xev creates a window and then asks the X server to send it events whenever anything happens to the window (such as it being moved, resized, typed in, clicked in, etc.). You can also attach it to an existing window. It is useful for seeing what causes events to occur and to display the information that they contain; it is essentially a debugging and development tool, and should not be needed in normal usage.
builddeps  :
    - pkgconfig(xrandr)
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
